name: automatic analysis

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "sunrise"
logo: "/assets/images/logo.png"
title: automatic analysis
subtitle: "a MATLAB pipeline"
title_separator: "|"
markdown: kramdown
include: ["_pages"]
plugins: 
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
   # news
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false
      share: false
 

repository: "automaticanalysis/automaticanalysis"
